name: fast-d3dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=23.0
  - numpy<2.0.0
  - pytorch=2.0.1
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - faiss-gpu
  - tqdm
  - plyfile
  - pip:
    - "numpy<2.0.0"
    - websockets
    - opencv-python
    - imageio
    - lpips
    - scipy
    - tensorboard
    - submodules/diff-gaussian-rasterization_fastgs
    - submodules/diff-flow-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - tinycudann